mutation TransactionsCreate($bill: CreateTransactions_TransactionInput!) {
  createTransactions_Transaction(input: $bill) {
    clientMutationId
    transactionsTransactionEdge {
      node {
        id
        header {
          referenceNumber
          amount
        }
      }
    }
  }
}
